// @generated by protoc-gen-es v2.15.0 with parameter "target=ts,import_extension=js"
// @generated from file greet.proto (package greet.v1, syntax proto3)
/* eslint-disable */

import type {
  GenFile,
  GenMessage,
  GenService,
} from '@bufbuild/protobuf/codegenv2';
import {
  fileDesc,
  messageDesc,
  serviceDesc,
} from '@bufbuild/protobuf/codegenv2';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file greet.proto.
 */
export const file_greet: GenFile /*@__PURE__*/ = fileDesc(
  'CgtncmVldC5wcm90bxIIZ3JlZXQudjEiGgoKU2F5UmVxdWVzdBIMCgRuYW1lGAEgASgJIiwKC1NheVJlc3BvbnNlEgwKBHRleHQYASABKAkSDwoHZ3JlZXRlZBgCIAEoBSIuChBDb3VudGRvd25SZXF1ZXN0EgwKBG5hbWUYASABKAkSDAoEZnJvbRgCIAEoBTKIAQoMR3JlZXRTZXJ2aWNlEjQKA1NheRIULmdyZWV0LnYxLlNheVJlcXVlc3QaFS5ncmVldC52MS5TYXlSZXNwb25zZSIAEkIKCUNvdW50ZG93bhIaLmdyZWV0LnYxLkNvdW50ZG93blJlcXVlc3QaFS5ncmVldC52MS5TYXlSZXNwb25zZSIAMAFiBnByb3RvMw',
);

/**
 * @generated from message greet.v1.SayRequest
 */
export type SayRequest = Message<'greet.v1.SayRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message greet.v1.SayRequest.
 * Use `create(SayRequestSchema)` to create a new message.
 */
export const SayRequestSchema: GenMessage<SayRequest> /*@__PURE__*/ =
  messageDesc(file_greet, 0);

/**
 * @generated from message greet.v1.SayResponse
 */
export type SayResponse = Message<'greet.v1.SayResponse'> & {
  /**
   * @generated from field: string text = 1;
   */
  text: string;

  /**
   * How many greetings the injected Greetings service has counted.
   *
   * @generated from field: int32 greeted = 2;
   */
  greeted: number;
};

/**
 * Describes the message greet.v1.SayResponse.
 * Use `create(SayResponseSchema)` to create a new message.
 */
export const SayResponseSchema: GenMessage<SayResponse> /*@__PURE__*/ =
  messageDesc(file_greet, 1);

/**
 * @generated from message greet.v1.CountdownRequest
 */
export type CountdownRequest = Message<'greet.v1.CountdownRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 from = 2;
   */
  from: number;
};

/**
 * Describes the message greet.v1.CountdownRequest.
 * Use `create(CountdownRequestSchema)` to create a new message.
 */
export const CountdownRequestSchema: GenMessage<CountdownRequest> /*@__PURE__*/ =
  messageDesc(file_greet, 2);

/**
 * @generated from service greet.v1.GreetService
 */
export const GreetService: GenService<{
  /**
   * @generated from rpc greet.v1.GreetService.Say
   */
  say: {
    methodKind: 'unary';
    input: typeof SayRequestSchema;
    output: typeof SayResponseSchema;
  };
  /**
   * @generated from rpc greet.v1.GreetService.Countdown
   */
  countdown: {
    methodKind: 'server_streaming';
    input: typeof CountdownRequestSchema;
    output: typeof SayResponseSchema;
  };
}> /*@__PURE__*/ = serviceDesc(file_greet, 0);
