/**
 * The social card, drawn once and committed as `public/og.png`.
 *
 * `renderPage` had no `og:image` because every image the site ships is an SVG
 * and the unfurlers decline to render one, so a share of any dunx page produced
 * a bare link. That suppresses exactly the sharing that earns the links a new
 * domain needs.
 *
 * `Bun.Image` cannot help: it decodes JPEG, PNG, WebP, GIF, BMP, TIFF, HEIC and
 * AVIF, and an SVG handed to it fails `ERR_IMAGE_UNKNOWN_FORMAT` (probed on Bun
 * 1.4.2). So the card is HTML screenshotted through the `Bun.WebView` the
 * `browser` phase already drives, which needs no new dependency and no
 * rasteriser.
 *
 * It is committed rather than generated by `docs:build` for the same reason the
 * coverage badges are: the deploy job would otherwise need a Chrome, and one
 * headline change every few months is not worth that. `bun run gen:og`
 * regenerates it.
 *
 * The words come from `scripts/positioning.ts`, so the card cannot say something
 * the hero and the README do not.
 */

import { writeFileSync } from 'node:fs';
import { BLURB, CHIPS, HEADLINE } from '../../../scripts/positioning.js';
import { escapeHtml } from './prerender.js';

const WIDTH = 1200;
const HEIGHT = 630;

/** The logo mark's own stops, so the card's accent is the wordmark's accent. */
const CYAN = '#22b8cf';
const INDIGO = '#4c6ef5';
const VIOLET = '#7950f2';

const LOGO = `<svg viewBox="0 0 32 32" width="64" height="64" fill="none" aria-hidden="true">
  <linearGradient id="c" x1="4" y1="4" x2="28" y2="28" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="${CYAN}" />
    <stop offset=".5" stop-color="${INDIGO}" />
    <stop offset="1" stop-color="${VIOLET}" />
  </linearGradient>
  <g stroke="url(#c)" stroke-width="4" stroke-linecap="round">
    <path d="M5.9 5.6H15.7a10.4 10.4 0 0 1 0 20.8H5.9" />
    <path d="m9.7 11.4 9.2 9.2m0-9.2-9.2 9.2" />
  </g>
</svg>`;

export const cardHtml = (): string => `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { width: ${WIDTH}px; height: ${HEIGHT}px; }
  body {
    position: relative;
    overflow: hidden;
    background:
      radial-gradient(900px 520px at 88% -8%, rgba(76, 110, 245, 0.28), transparent 70%),
      radial-gradient(760px 460px at 4% 106%, rgba(121, 80, 242, 0.22), transparent 70%),
      linear-gradient(140deg, #080c19 0%, #101736 58%, #0a0f24 100%);
    color: #f4f6fb;
    font-family: 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  /* The 54px lattice the hero uses, faded out the same way. */
  .grid {
    position: absolute; inset: 0;
    background-image:
      linear-gradient(to right, rgba(148, 163, 184, 0.10) 1px, transparent 1px),
      linear-gradient(to bottom, rgba(148, 163, 184, 0.10) 1px, transparent 1px);
    background-size: 54px 54px;
    mask-image: radial-gradient(120% 100% at 50% 0%, #000 35%, transparent 78%);
  }
  /* space-between rather than a pair of auto top margins, which fought each
     other and pushed the chips off the 630px canvas. */
  .card {
    position: relative; height: 100%; padding: 56px 68px;
    display: flex; flex-direction: column; justify-content: space-between;
  }
  .brand { display: flex; align-items: center; gap: 16px; }
  .brand span { font-size: 46px; font-weight: 700; letter-spacing: -0.02em; }
  h1 {
    font-size: 58px; line-height: 1.1; font-weight: 800; letter-spacing: -0.03em;
  }
  .accent {
    background-image: linear-gradient(96deg, #748ffc, #9775fa 42%, #3bc9db);
    -webkit-background-clip: text; background-clip: text; color: transparent;
  }
  p { margin-top: 20px; font-size: 24px; line-height: 1.45; color: #aab4c8; max-width: 53ch; }
  .chips { display: flex; gap: 12px; }
  .chip {
    padding: 9px 18px; border-radius: 9px; font-size: 21px;
    border: 1px solid rgba(148, 163, 184, 0.28); color: #ccd4e4;
    font-family: ui-monospace, 'SFMono-Regular', Menlo, monospace;
  }
  .chip:first-child { border-color: rgba(116, 143, 252, 0.6); color: #b9c6ff; }
</style>
</head>
<body>
  <div class="grid"></div>
  <div class="card">
    <div class="brand">${LOGO}<span>dunx</span></div>
    <div>
      <h1>${escapeHtml(HEADLINE[0])}<br /><span class="accent">${escapeHtml(HEADLINE[1])}</span></h1>
      <p>${escapeHtml(BLURB)}</p>
    </div>
    <div class="chips">
      ${CHIPS.map((chip) => `<span class="chip">${escapeHtml(chip)}</span>`).join('')}
    </div>
  </div>
</body>
</html>
`;

export const renderCard = async (target: string): Promise<number> => {
  const html = cardHtml();
  const server = Bun.serve({
    port: 0,
    fetch: () =>
      new Response(html, { headers: { 'content-type': 'text/html' } }),
  });

  const view = new Bun.WebView({ width: WIDTH, height: HEIGHT });
  try {
    // `cdp()` has no session until something has been navigated to, so the
    // order is fixed: navigate, then override, then let the resize repaint.
    await view.navigate(server.url.origin);
    // Exactly the declared `og:image:width`/`height`, at a ratio of 1. A retina
    // capture would be sharper and would then disagree with the tags, and the
    // unfurlers scale to their own slot anyway.
    await view.cdp('Emulation.setDeviceMetricsOverride', {
      width: WIDTH,
      height: HEIGHT,
      deviceScaleFactor: 1,
      mobile: false,
    });
    // The gradient text and the mask settle a frame after layout, the same wait
    // `preview.ts` takes before a shot.
    await Bun.sleep(400);

    const bytes = new Uint8Array(await (await view.screenshot()).arrayBuffer());
    writeFileSync(target, bytes);
    return bytes.byteLength;
  } finally {
    view.close();
    await server.stop(true);
  }
};

if (import.meta.main) {
  const target = Bun.fileURLToPath(
    new URL('../public/og.png', import.meta.url),
  );
  const bytes = await renderCard(target);
  console.log(`og:image: ${WIDTH}x${HEIGHT}, ${(bytes / 1024).toFixed(1)} KB`);
}
