/** The binary a compiled build writes, from the package name's last segment. */
export const binaryName = (name: string): string =>
  name.split('/').at(-1) ?? name;

/**
 * The `scripts/build.ts` a `binary` scaffold gets. `Bun.build` takes both the
 * `@dunx/transform` plugin and `compile`, so the constructor-dependency records
 * the container resolves are baked into the executable at build time - a compiled
 * binary has no load-time plugin to record them.
 */
export const buildScript = (name: string): string =>
  `// Generated by @dunx/create-app for ${name}. Yours to edit.
import { depsPlugin } from '@dunx/transform';
import { join, resolve } from 'node:path';

const DIR = resolve(import.meta.dir, '..');
const outfile = join(DIR, 'dist', '${binaryName(name)}');

const compiled = await Bun.build({
  entrypoints: [join(DIR, 'src/main.ts')],
  target: 'bun',
  // One self-contained executable: the Bun runtime plus the app in one file, so a
  // host needs nothing installed to run it.
  compile: { outfile },
  plugins: [depsPlugin],
  minify: true,
  // A stack trace is never read off a shipped binary; symbols would only add size.
  sourcemap: 'none',
  tsconfig: join(DIR, 'tsconfig.json'),
});

if (!compiled.success) {
  for (const log of compiled.logs) console.error(log);
  throw new AggregateError(compiled.logs, 'compile failed');
}

const bytes = await Bun.file(outfile).bytes();
console.log(
  \`Built \${(bytes.byteLength / 1024 / 1024).toFixed(1)} MB -> \${outfile}\`,
);
`;
