import { BASE_CONFIG, CONFIG_GROUPS, type Feature } from './features.js';

/**
 * The wiring, generated from a feature selection.
 *
 * The full example states every feature at once in three files - `app.module.ts`,
 * `config.ts` and `main.ts` - so those are the ones a subset cannot copy.
 * Everything else is the feature's own directory, copied verbatim.
 *
 * Generated rather than assembled by editing a copy on purpose: an edited copy
 * cannot be checked against the example it came from, and the byte-for-byte parity
 * test is what stops the vendored features drifting from the app CI actually boots.
 */
const HEADER = (name: string): string =>
  `// Generated by @dunx/create-app for ${name}. Yours to edit.\n`;

const uniq = (values: readonly string[]): string[] => [...new Set(values)];

/** Every config group the selection needs, base first, in a stable order. */
export const configGroupsFor = (
  features: readonly Feature[],
): readonly string[] => {
  const wanted = uniq([
    ...BASE_CONFIG,
    ...features.flatMap((feature) => feature.config),
  ]);
  return Object.keys(CONFIG_GROUPS).filter((group) => wanted.includes(group));
};

const dependenciesFor = (features: readonly Feature[]): readonly string[] =>
  uniq([
    '@dunx/core',
    '@dunx/http',
    '@dunx/transform',
    '@dunx/infra',
    ...features.flatMap((feature) => feature.dependencies),
  ]).sort();

const DUNX = /^@dunx\//;

export const manifest = (features: readonly Feature[]): string => {
  const deps = dependenciesFor(features);
  const dependencies: Record<string, string> = {};
  for (const dep of deps) {
    dependencies[dep] = DUNX.test(dep) ? '__DUNX_VERSION__' : versionOf(dep);
  }

  // `--watch` restarts the process on a change rather than swapping modules in
  // place: a container is built once at boot, so `--hot` would leave the old
  // providers holding the sockets the new ones are trying to bind.
  const scripts: Record<string, string> = {
    dev: 'bun --watch src/main.ts',
    start: 'bun src/main.ts',
    test: 'bun test',
    typecheck: 'tsc --noEmit',
  };

  return `${JSON.stringify(
    {
      name: '__DUNX_APP_NAME__',
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts,
      dependencies,
      devDependencies: {
        '@dunx/testing': '__DUNX_VERSION__',
        '@types/bun': '>=1.4.1',
        typescript: '^5.7.0',
      },
      engines: { bun: '>=1.4.1' },
    },
    null,
    2,
  )}\n`;
};

/**
 * Third-party versions, exact for the reason dunx's own manifests are, and
 * written here rather than read off `examples/full` at run time:
 * the generated app installs from npm and the example installs from the workspace,
 * so the example's manifest is not a statement about what a consumer should take.
 * `features.test.ts` checks these against the example's, which is what stops them
 * silently diverging from a version combination that is actually exercised.
 */
export const THIRD_PARTY: Readonly<Record<string, string>> = Object.freeze({
  zod: '4.5.4',
  'drizzle-orm': '0.45.2',
  'better-auth': '1.6.25',
  bullmq: '6.0.5',
  ioredis: '6.0.0',
});

const versionOf = (dep: string): string => THIRD_PARTY[dep] ?? 'latest';

export const appModule = (
  name: string,
  features: readonly Feature[],
): string => {
  const needsLogger = true;
  // `OpenApiModule` wraps this module rather than being imported by it, so its
  // factory resolves `Auth` from here - see `main`.
  const documentsAuth = has(features, 'openapi') && has(features, 'auth');
  const imports = [
    ...(documentsAuth ? ["import { Auth } from '@dunx/auth';"] : []),
    "import { ConfigModule, Module } from '@dunx/core';",
    ...(needsLogger
      ? ["import { LoggerModule } from '@dunx/infra/logger';"]
      : []),
    "import { AppConfigService, validate } from './config.js';",
    ...features.map(
      (feature) =>
        `import { ${feature.module.klass} } from '${feature.module.from}';`,
    ),
  ];

  const moduleImports = [
    'ConfigModule.forRoot({ validate, as: AppConfigService }),',
    '// The level comes from the validated config, which is the one thing a',
    '// zero-argument `forRoot` function cannot reach.',
    'LoggerModule.forRootAsync(',
    '  {',
    '    useFactory: (config: AppConfigService) => ({',
    "      name: config.get('appName'),",
    "      level: config.get('log').level,",
    '    }),',
    '    inject: [AppConfigService] as const,',
    '  },',
    '  { captureGlobalErrors: true },',
    '),',
    ...features.map((feature) => `${feature.module.klass},`),
  ];

  return `${HEADER(name)}${imports.join('\n')}

/**
 * Import order is construction order, and shutdown runs in reverse - so config and
 * the logger are built first and torn down last, and anything a feature depends on
 * outlives it.
 */
@Module({
  imports: [
${moduleImports.map((line) => `    ${line}`).join('\n')}
  ],${
    documentsAuth
      ? `
  // Better Auth serves its own routes, so the document is the only place they
  // appear - and \`betterAuthDocument\` needs the instance.
  exports: [Auth],`
      : ''
  }
})
export class AppModule {}
`;
};

export const config = (name: string, groups: readonly string[]): string => {
  const chosen = groups
    .map((group) => [group, CONFIG_GROUPS[group]] as const)
    .filter(
      (entry): entry is [string, (typeof CONFIG_GROUPS)[string]] =>
        entry[1] !== undefined,
    );

  const schema = chosen.flatMap(([, group]) => group.schema);
  const needsLogLevel = groups.includes('log');

  return `${HEADER(name)}import { ConfigService, type ConfigSource${
    needsLogLevel ? ', LogLevel' : ''
  } } from '@dunx/core';
import { z } from 'zod';

/**
 * One validation function, which is the whole \`ConfigModule\` contract. dunx does
 * not pick the library - this is zod because the routes already use it, and a
 * hand-written function that throws would work identically.
 *
 * \`.default()\` is where a value comes from when the variable is unset, so a clean
 * checkout boots with no \`.env\` at all. Bun loads \`.env\` and \`.env.local\` itself,
 * so there is nothing here that reads a file.
 */
const envSchema = z.object({
${schema.map((line) => `  ${line}`).join('\n')}
});

export interface AppConfig {
${chosen.map(([, group]) => `  ${group.field}`).join('\n')}
}

/**
 * One name for the typed config everywhere. A subclass rather than
 * \`ConfigService<AppConfig>\` at each site because a factory's \`inject: [...]\`
 * carries no type argument - the class does, and it is a real runtime value, so it
 * is both a precise token and a usable constructor annotation.
 */
export class AppConfigService extends ConfigService<AppConfig> {}

/** The one broker channel the websocket relay carries every topic on. */
export const RELAY_CHANNEL = '__DUNX_APP_NAME__:ws';

/** Flat variables in, a shaped object out. Nothing downstream reads \`Bun.env\`. */
export const validate = (env: ConfigSource): AppConfig => {
  const parsed = envSchema.safeParse(env);
  if (!parsed.success) {
    const issues = parsed.error.issues
      .map((issue) => \`\${issue.path.join('.') || '(root)'}: \${issue.message}\`)
      .join('\\n - ');
    throw new Error(\`Configuration is invalid:\\n - \${issues}\`);
  }
  const value = parsed.data;

  return {
${chosen.map(([, group]) => `    ${group.map}`).join('\n')}
  };
};
`;
};

const has = (features: readonly Feature[], name: string): boolean =>
  features.some((feature) => feature.name === name);

export const main = (name: string, features: readonly Feature[]): string => {
  const openapi = has(features, 'openapi');
  const websockets = has(features, 'websockets');
  const http = has(features, 'http');
  const health = has(features, 'health');
  const documentsAuth = openapi && has(features, 'auth');
  // Both bind a middleware class that the **app** registers rather than the module:
  // position in the chain is the app's decision, so it is generated here.
  const assets = has(features, 'assets');
  const throttle = has(features, 'throttle');

  const imports = [
    ...(documentsAuth
      ? ["import { Auth, betterAuthDocument } from '@dunx/auth';"]
      : []),
    "import { Logger } from '@dunx/core';",
    `import { ${[
      'HttpFactory',
      ...(websockets ? ['RedisRelay'] : []),
      ...(assets ? ['StaticFiles'] : []),
      ...(throttle ? ['ThrottleGuard'] : []),
      'type HttpApp',
    ].join(', ')} } from '@dunx/http';`,
    ...(openapi ? ["import { OpenApiModule } from '@dunx/openapi';"] : []),
    "import { AppModule } from './app.module.js';",
    `import { ${['AppConfigService', ...(websockets ? ['RELAY_CHANNEL'] : [])].join(', ')} } from './config.js';`,
    ...(http
      ? ["import { RequestTrailMiddleware } from './http/request-trail.js';"]
      : []),
  ];

  /**
   * `forRootAsync` once Better Auth is in: it answers `/api/auth/*` from its own
   * handler, so route discovery sees none of it and `contribute` is what puts its
   * paths in the document. The factory needs the instance, and there is no
   * container while the module graph is still being described.
   */
  const root = documentsAuth
    ? `OpenApiModule.forRootAsync({
      root: AppModule,
      inject: [Auth] as const,
      useFactory: (auth: Auth) => ({
        title: '__DUNX_APP_NAME__',
        version: '0.1.0',
        contribute: [
          betterAuthDocument(auth, { basePath: '/api/auth', tag: 'Auth' }),
        ],
      }),
    })`
    : openapi
      ? `OpenApiModule.forRoot({
      title: '__DUNX_APP_NAME__',
      version: '0.1.0',
      root: AppModule,
    })`
      : 'AppModule';

  const options = [
    // Per-route counts and timings, folded into the entry request logging already
    // builds: +35.2 ns a request. `DbModule` is scaffolded with `metrics: true`
    // to match, so `QueryMetrics` has something in it.
    ...(has(features, 'stats') ? ['metrics: true,'] : []),
    ...(websockets
      ? [
          '// Multi-node websocket fan-out on `Bun.RedisClient`, so it costs no',
          '// dependency. With no Redis running this degrades to single-process',
          '// behaviour, logs one warning, and the app still boots.',
          'websocket: { idleTimeout: 30 },',
          'relay: new RedisRelay({ connectionTimeout: 500 }),',
          'relayChannel: RELAY_CHANNEL,',
        ]
      : []),
  ];

  /**
   * Everything between `create()` and `listen()`. The prefix is set whatever is
   * selected, because the copied controllers declare paths under it and the URLs
   * printed at boot assume it.
   *
   * `app.use` takes the middleware **class**, not an instance: the container
   * constructs it, which is what lets it have dependencies of its own.
   */
  const shaping = [
    "app.setGlobalPrefix('api');",
    // Assets first, and outside the prefix: a page pulling twenty hashed bundles
    // must not spend a caller's request budget, and middleware never gets the
    // prefix because it is not a discovered route.
    ...(assets ? ['app.use(StaticFiles);'] : []),
    ...(http
      ? [
          'app.use(RequestTrailMiddleware);',
          "app.set('trust proxy', true);",
          'app.enableCors({',
          "  origin: app.get(AppConfigService).get('corsOrigin'),",
          '  credentials: true,',
          '  maxAge: 600,',
          '});',
        ]
      : []),
    // After anything that establishes who is calling, because the subject the
    // limit counts by is what that decides.
    ...(throttle ? ['app.use(ThrottleGuard);'] : []),
  ];

  const urls = [
    ...(openapi
      ? [
          "logger.info(`docs    ${new URL('api/docs', url).href}`);",
          "logger.info(`openapi ${new URL('api/openapi.json', url).href}`);",
        ]
      : []),
    ...(health
      ? ["logger.info(`health  ${new URL('api/health', url).href}`);"]
      : []),
  ];

  return `${HEADER(name)}${imports.join('\n')}

/**
 * One app for \`bun run start\`, \`bun run dev\` and the tests, and one file:
 * \`createApp\` is exported for a caller that wants the shape without a server, and
 * the block at the bottom serves it when this file is the entry point.
 *
 * \`create()\` boots the container and discovers routes and gateways; \`listen()\` is
 * what builds the \`Bun.serve\` route table. Everything between the two still gets to
 * shape it, and after \`listen()\` every one of those throws.
 */
export const createApp = async (): Promise<HttpApp> => {
  const app = await HttpFactory.create(
    ${root}${
      options.length === 0
        ? ',\n'
        : `,
    {
${options.map((line) => `      ${line}`).join('\n')}
    },
`
    }  );

${shaping.map((line) => `  ${line}`).join('\n')}

  return app;
};

const start = async (): Promise<void> => {
  const app = await createApp();
  app.enableShutdownHooks();

  const config = app.get(AppConfigService);
  const logger = app.get(Logger);
  const url = await app.listen(config.get('port'));

  logger.info(\`listening on \${url}\`);
${urls.map((line) => `  ${line}`).join('\n')}${urls.length > 0 ? '\n' : ''}
  // Nothing else to do: the server holds the process open, and the shutdown hooks
  // resolve this once a signal arrives.
  await app.closed;
};

// False when a test imports this file for \`createApp\` alone, which is what lets one
// module be both the entry point and the app's definition.
if (import.meta.main) {
  start().catch((error: unknown) => {
    console.error('failed to start', error);
    process.exit(1);
  });
}
`;
};

export const envExample = (groups: readonly string[]): string => {
  const lines = groups
    .flatMap((group) => CONFIG_GROUPS[group]?.env ?? [])
    .map((entry) => `${entry.name}=${entry.value}`);

  return lines.length === 0
    ? '# Every variable has a default, so this file is optional.\n'
    : `# Every variable here has a default, so the app boots with no .env at all.\n${lines.join('\n')}\n`;
};

export const readme = (name: string, features: readonly Feature[]): string => {
  const services = features.filter((feature) => feature.service !== undefined);

  return `# ${name}

Scaffolded with \`bunx @dunx/create-app\`.

\`\`\`bash
bun install
bun run dev     # restarts on a change
bun run start
\`\`\`

## What is wired up

${
  features.length === 0
    ? 'Nothing beyond the base app.'
    : features
        .map((feature) => `- **${feature.name}** - ${feature.summary}`)
        .join('\n')
}

${
  services.length === 0
    ? ''
    : `## Services

These features need something running. Each one degrades rather than failing the
boot, so the app still starts without them.

${services.map((feature) => `- **${feature.name}** needs ${feature.service}`).join('\n')}

`
}## Layout

- \`src/main.ts\` - exports \`createApp\`, and serves it when run directly
- \`src/app.module.ts\` - the root module, importing every feature
- \`src/config.ts\` - one validation function, flat env in and a shaped object out
${features.map((feature) => `- \`src/${feature.source}/\` - ${feature.name}`).join('\n')}

\`main.ts\`, \`app.module.ts\` and \`config.ts\` were generated for the features you
chose; everything else is copied from dunx's \`examples/full\`, which is run and
toured in CI on every push. The \`*.demo.ts\` files are that example's scripted
walkthroughs - delete one and its \`providers\` entry when you do not want it.

A test imports \`createApp\` from \`./main.js\` and never starts a server: the
\`import.meta.main\` block at the bottom of the file is false for an import.

## Constructor injection

\`bunfig.toml\` preloads \`@dunx/transform\`, which records each class's constructor
parameter types so the container can resolve them. Without that line providers are
built with no arguments and boot fails saying so.
`;
};
