/** The banner every generated file opens with. */
export const HEADER = (name: string): string =>
  `// Generated by @dunx/create-app for ${name}. Yours to edit.\n`;

export const uniq = (values: readonly string[]): string[] => [
  ...new Set(values),
];
