import type { Subject } from './types.js';

export const subjects: readonly Subject[] = [
  {
    id: 'bun-serve',
    label: 'Bun.serve (raw)',
    runtime: 'bun',
    entry: 'servers/bun-serve.ts',
    preload: [],
    versionOf: null,
    validator: 'zod (hand-wired)',
    notes: [
      'The ceiling. @dunx/http is a layer on top of this exact API, so the gap between them is dunx overhead and nothing else.',
      'Uses Bun.serve({ routes }) - the same native router @dunx/http dispatches through.',
    ],
  },
  {
    id: 'dunx',
    label: '@dunx/http',
    runtime: 'bun',
    entry: 'servers/dunx.ts',
    preload: ['@dunx/transform/preload'],
    versionOf: '@dunx/http',
    validator: 'zod (Standard Schema)',
    notes: [
      'Runs with the @dunx/transform preload and one constructor-injected service, which is how a real dunx app is written.',
      'DI resolution and route discovery happen at boot, so they show up in the startup number and not in the per-request number.',
    ],
  },
  {
    id: 'dunx-logging',
    label: '@dunx/http (+ request logging)',
    runtime: 'bun',
    entry: 'servers/dunx-logging.ts',
    preload: ['@dunx/transform/preload'],
    versionOf: '@dunx/http',
    validator: 'zod (Standard Schema)',
    notes: [
      'The same app as `dunx` with `requestLogging` left at its default, so the cost of one structured entry per request is visible rather than folded into the framework number.',
      'No other subject logs anything, which is why this is a separate row and not the primary one.',
    ],
  },
  {
    id: 'elysia',
    label: 'Elysia',
    runtime: 'bun',
    entry: 'servers/elysia.ts',
    preload: [],
    versionOf: 'elysia',
    validator: 'zod (Standard Schema)',
    notes: [
      'Bun-native. Given zod rather than its own TypeBox validator so the validate scenario stays comparable; TypeBox is compiled and would be faster.',
    ],
  },
  {
    id: 'nest-express',
    label: 'NestJS (Express)',
    runtime: 'node',
    entry: 'servers/nest/nest-express.ts',
    preload: [],
    versionOf: '@nestjs/core',
    validator: 'zod (pipe)',
    notes: [
      'dunx is deliberately Nest-shaped - modules, controllers, DI, guards - so this is the most direct answer to what that programming model costs.',
      'The default adapter, which is what most Nest apps ship. Compare against the `express` row to separate Nest from the server underneath it.',
      'The one subject using legacy decorators and reflect-metadata, which Nest requires; see servers/nest/tsconfig.json.',
    ],
  },
  {
    id: 'nest-fastify',
    label: 'NestJS (Fastify)',
    runtime: 'node',
    entry: 'servers/nest/nest-fastify.ts',
    preload: [],
    versionOf: '@nestjs/core',
    validator: 'zod (pipe)',
    notes: [
      'The same Nest application on the Fastify adapter, so the pair isolates the adapter from the framework the way hono-bun/hono-node isolates the runtime.',
    ],
  },
  {
    id: 'hono-bun',
    label: 'Hono (Bun)',
    runtime: 'bun',
    entry: 'servers/hono.ts',
    preload: [],
    versionOf: 'hono',
    validator: 'zod (@hono/zod-validator)',
    notes: [
      'Hono on Bun.serve, so it shares the runtime with Bun.serve, dunx and Elysia.',
    ],
  },
  {
    id: 'hono-node',
    label: 'Hono (Node)',
    runtime: 'node',
    entry: 'servers/hono-node.ts',
    preload: [],
    versionOf: 'hono',
    validator: 'zod (@hono/zod-validator)',
    notes: [
      'The same Hono app on node:http via @hono/node-server. Included so one framework appears on both runtimes and the runtime term can be separated from the framework term.',
    ],
  },
  {
    id: 'node-http',
    label: 'node:http (raw)',
    runtime: 'node',
    entry: 'servers/node-http.ts',
    preload: [],
    versionOf: null,
    validator: 'zod (hand-wired)',
    notes: [
      'The Node ceiling: a bare requestListener with a hand-rolled switch, no framework. Routing is a startsWith chain, which is faster than any real router.',
    ],
  },
  {
    id: 'fastify',
    label: 'Fastify (Node)',
    runtime: 'node',
    entry: 'servers/fastify.ts',
    preload: [],
    versionOf: 'fastify',
    validator: 'zod (validatorCompiler)',
    notes: [
      'Given zod through its validatorCompiler hook rather than its default ajv/JSON Schema path, so the validate scenario stays comparable. Ajv compiles to straight-line JS and is materially faster than zod - this understates Fastify on that one scenario.',
      'No response schema is set, so serialisation is JSON.stringify rather than fast-json-stringify, matching every other subject.',
    ],
  },
  {
    id: 'express',
    label: 'Express (Node)',
    runtime: 'node',
    entry: 'servers/express.ts',
    preload: [],
    versionOf: 'express',
    validator: 'zod (hand-wired)',
    notes: ['Express 5 with express.json() for the validate scenario only.'],
  },
  {
    id: 'nethttp',
    label: 'net/http (Go)',
    runtime: 'go',
    entry: 'servers/go/cmd/nethttp/main.go',
    preload: [],
    versionOf: null,
    validator: 'go-playground/validator v10',
    notes: [
      'The Go ceiling, mirroring node:http and bun-serve for their runtimes: the standard library and nothing else.',
      'Routing is http.ServeMux with Go 1.22 method-and-wildcard patterns, so the router is native the same way Bun.serve({ routes }) is.',
      'runtime.GOMAXPROCS(1). Go would otherwise use all 32 cores while every other subject uses one, which measures the machine and not the framework.',
      'Compiled before the run. The startup column times the binary, not `go build`.',
    ],
  },
  {
    id: 'gin',
    label: 'Gin (Go)',
    runtime: 'go',
    entry: 'servers/go/cmd/gin/main.go',
    preload: [],
    versionOf: 'github.com/gin-gonic/gin',
    validator: 'gin binding (go-playground/validator v10)',
    notes: [
      "The Go framework Elysia's landing page compares itself against, which is why it is here.",
      'gin.New(), not gin.Default(): Default installs a per-request logger and a recovery middleware, and nothing else in this suite logs or recovers.',
      'runtime.GOMAXPROCS(1), for the reason on the net/http row.',
      'Compiled before the run. The startup column times the binary, not `go build`.',
    ],
  },
  {
    id: 'axum',
    label: 'Axum (Rust)',
    runtime: 'rust',
    entry: 'servers/rust/src/axum.rs',
    preload: [],
    versionOf: 'axum',
    validator: 'validator crate (derive)',
    notes: [
      'Axum on tokio, hyper underneath, no tower layers.',
      'A single-threaded tokio runtime (flavor = "current_thread"), for the same reason Go is pinned to one core.',
      'Built with a plain `cargo build --release`: no LTO, no codegen-units=1, no profile overrides that nothing else in this suite gets.',
      'Compiled before the run. The startup column times the binary, not `cargo build`.',
    ],
  },
  {
    id: 'spring',
    label: 'Spring Boot (JVM)',
    runtime: 'jvm',
    entry: 'servers/java/src/main/java/bench/App.java',
    preload: [],
    versionOf: 'spring-boot-starter-parent',
    validator: 'jakarta.validation (Hibernate Validator)',
    warmupFloorSeconds: 30,
    notes: [
      'Spring Boot on its default stack: Spring MVC over embedded Tomcat, Jackson, Hibernate Validator. No AOT, no CDS, no native image, no JVM flags.',
      'Warmed for 30 seconds rather than the 3 every other subject gets, because 3 does not warm a JIT and a cold JVM number would be as dishonest as a flattering one.',
      'Tomcat is pinned to one worker thread, for the same reason Go and tokio are pinned to one core.',
      'Packaged before the run. The startup column times `java -jar`, not `mvn package` - and unlike the compiled subjects that startup includes class loading and JIT-free first execution, which is a real cost and not an artefact.',
    ],
  },
  {
    id: 'aspnet-minimal',
    label: 'ASP.NET Core minimal APIs',
    runtime: 'dotnet',
    entry: 'servers/dotnet/aspnet-minimal/Program.cs',
    preload: [],
    versionOf: 'TargetFramework',
    validator: 'DataAnnotations (hand-wired)',
    warmupFloorSeconds: 30,
    env: { DOTNET_PROCESSOR_COUNT: '1' },
    notes: [
      'Kestrel and the endpoint router with routes declared as lambdas, which is the .NET floor in the same sense node-http and bun-serve are their runtimes.',
      'DOTNET_PROCESSOR_COUNT=1 and a thread pool capped at one worker, for the reason on the net/http row. The process refuses to start unpinned rather than quietly measuring 32 cores.',
      'Validation is hand-wired against the in-box DataAnnotations validator, the way bun-serve and node-http hand-wire zod - minimal APIs have no model-validation filter of their own.',
      'A malformed body gets a bare 400 from the framework here, where every other subject answers {"error":"Invalid body"}. That path is not measured, and matching it would mean an exception-handler middleware on every request, which is.',
      'Warmed for 30 seconds rather than 3, for the reason on the Spring Boot row: tiered JIT. At 3 seconds it measured 40k req/s on the json scenario and was still climbing 20 seconds later, plateauing near 88k.',
      'Published before the run. The startup column times `dotnet aspnet-minimal.dll`, not `dotnet publish` - and like the JVM that startup includes JIT-free first execution, which is a real cost and not an artefact.',
    ],
  },
  {
    id: 'aspnet-mvc',
    label: 'ASP.NET Core MVC',
    runtime: 'dotnet',
    entry: 'servers/dotnet/aspnet-mvc/Program.cs',
    preload: [],
    versionOf: 'TargetFramework',
    validator: 'DataAnnotations ([ApiController])',
    warmupFloorSeconds: 30,
    env: { DOTNET_PROCESSOR_COUNT: '1' },
    notes: [
      'Attribute-routed controllers, model binding, [ApiController] validation and a controller resolved from the DI container on every request - the same programming model as the Spring and NestJS rows, and the one dunx borrows its shape from.',
      'The pair with aspnet-minimal isolates MVC from the runtime and the server underneath it, the way nest-express/express and hono-bun/hono-node isolate their one term.',
      'DOTNET_PROCESSOR_COUNT=1 and a thread pool capped at one worker, for the reason on the net/http row.',
      'Warmed for 30 seconds, for the reason on the aspnet-minimal row.',
      'Published before the run. The startup column times `dotnet aspnet-mvc.dll`, not `dotnet publish`.',
    ],
  },
  {
    id: 'django',
    label: 'Django (Python)',
    runtime: 'python',
    entry: 'servers/python/app.py',
    preload: [],
    versionOf: 'django',
    requires: 'django',
    validator: 'hand-written checks',
    notes: [
      'Django on gunicorn, one worker and one thread, for the same reason Go and tokio are pinned to one core. Not `runserver`, which reloads, threads and logs every request; and not `wsgiref.simple_server`, which serialises connections and measured 317 req/s at 64 of them.',
      'DEBUG off and MIDDLEWARE empty: the default stack adds sessions, auth, messages and CSRF, none of which the other subjects carry.',
      "Validation is hand-written rather than DRF. DRF is a separate framework and this row would then measure DRF; Django's own forms validate form-encoded input, not JSON.",
      '**Synchronous WSGI, and that is the honest caveat on this row.** Every other subject here speaks HTTP natively or through an event loop; a Django request handler blocks its worker for its whole duration. One gunicorn worker is the fair comparison against one core, and it is also not how anyone deploys Django - a real deployment runs several workers on several cores. Read this row as one worker against one worker, not as a capacity figure.',
      'Interpreted, so there is nothing to compile and no build time to report.',
    ],
  },
  {
    id: 'fastapi',
    label: 'FastAPI (Python)',
    runtime: 'python',
    entry: 'servers/python/fastapi_app.py',
    preload: [],
    versionOf: 'fastapi',
    requires: 'fastapi',
    validator: 'pydantic',
    notes: [
      'FastAPI on uvicorn, one worker, async ASGI. The closest cross-language comparison in this suite to what `@dunx/http` is for: declarative validation from a schema, with the types carried through to the handler.',
      '**`validate` is the scenario to read this row on.** dunx validates with zod through Standard Schema, Elysia with TypeBox, this with pydantic - the same job, three ecosystems. The other three scenarios are dispatch and serialisation, where FastAPI is carrying an ASGI stack the Bun subjects do not have.',
      'Validation is pydantic rather than hand-written, which is the opposite choice from the Django row. pydantic is how FastAPI is written rather than a separate framework bolted on the way DRF would be, so a hand-rolled check here would measure a FastAPI nobody deploys.',
      'The body is read and validated inside the handler rather than declared as a parameter. Same `model_validate_json` call either way; a declared parameter answers a rejection with FastAPI\'s own 422 and `detail` array, where every other subject answers 400 and `{"error":"Invalid body"}`, and the harness compares bytes on the success path only so it would not catch the divergence.',
      '`docs_url`, `redoc_url` and `openapi_url` are off. They mount three routes nothing in this suite calls.',
      'Plain asyncio, not `uvicorn[standard]`: no uvloop and no httptools. That is the floor rather than the ceiling, and it is what `pip install fastapi uvicorn` gives.',
      'Interpreted, so there is nothing to compile and no build time to report.',
    ],
  },
];
