import type { Subject } from './types.js';

export const subjects: readonly Subject[] = [
  {
    id: 'bun-serve',
    label: 'Bun.serve (raw)',
    runtime: 'bun',
    entry: 'servers/bun-serve.ts',
    preload: [],
    versionOf: null,
    validator: 'zod (hand-wired)',
    notes: [
      'The ceiling. @dunx/http is a layer on top of this exact API, so the gap between them is dunx overhead and nothing else.',
      'Uses Bun.serve({ routes }) - the same native router @dunx/http dispatches through.',
    ],
  },
  {
    id: 'dunx',
    label: '@dunx/http',
    runtime: 'bun',
    entry: 'servers/dunx.ts',
    preload: ['@dunx/transform/preload'],
    versionOf: '@dunx/http',
    validator: 'zod (Standard Schema)',
    notes: [
      'Runs with the @dunx/transform preload and one constructor-injected service, which is how a real dunx app is written.',
      'DI resolution and route discovery happen at boot, so they show up in the startup number and not in the per-request number.',
    ],
  },
  {
    id: 'dunx-logging',
    label: '@dunx/http (+ request logging)',
    runtime: 'bun',
    entry: 'servers/dunx-logging.ts',
    preload: ['@dunx/transform/preload'],
    versionOf: '@dunx/http',
    validator: 'zod (Standard Schema)',
    notes: [
      'The same app as `dunx` with `requestLogging` left at its default, so the cost of one structured entry per request is visible rather than folded into the framework number.',
      'No other subject logs anything, which is why this is a separate row and not the primary one.',
    ],
  },
  {
    id: 'elysia',
    label: 'Elysia',
    runtime: 'bun',
    entry: 'servers/elysia.ts',
    preload: [],
    versionOf: 'elysia',
    validator: 'zod (Standard Schema)',
    notes: [
      'Bun-native. Given zod rather than its own TypeBox validator so the validate scenario stays comparable; TypeBox is compiled and would be faster.',
    ],
  },
  {
    id: 'nest-express',
    label: 'NestJS (Express)',
    runtime: 'node',
    entry: 'servers/nest/nest-express.ts',
    preload: [],
    versionOf: '@nestjs/core',
    validator: 'zod (pipe)',
    notes: [
      'dunx is deliberately Nest-shaped - modules, controllers, DI, guards - so this is the most direct answer to what that programming model costs.',
      'The default adapter, which is what most Nest apps ship. Compare against the `express` row to separate Nest from the server underneath it.',
      'The one subject using legacy decorators and reflect-metadata, which Nest requires; see servers/nest/tsconfig.json.',
    ],
  },
  {
    id: 'nest-fastify',
    label: 'NestJS (Fastify)',
    runtime: 'node',
    entry: 'servers/nest/nest-fastify.ts',
    preload: [],
    versionOf: '@nestjs/core',
    validator: 'zod (pipe)',
    notes: [
      'The same Nest application on the Fastify adapter, so the pair isolates the adapter from the framework the way hono-bun/hono-node isolates the runtime.',
    ],
  },
  {
    id: 'hono-bun',
    label: 'Hono (Bun)',
    runtime: 'bun',
    entry: 'servers/hono.ts',
    preload: [],
    versionOf: 'hono',
    validator: 'zod (@hono/zod-validator)',
    notes: [
      'Hono on Bun.serve, so it shares the runtime with Bun.serve, dunx and Elysia.',
    ],
  },
  {
    id: 'hono-node',
    label: 'Hono (Node)',
    runtime: 'node',
    entry: 'servers/hono-node.ts',
    preload: [],
    versionOf: 'hono',
    validator: 'zod (@hono/zod-validator)',
    notes: [
      'The same Hono app on node:http via @hono/node-server. Included so one framework appears on both runtimes and the runtime term can be separated from the framework term.',
    ],
  },
  {
    id: 'node-http',
    label: 'node:http (raw)',
    runtime: 'node',
    entry: 'servers/node-http.ts',
    preload: [],
    versionOf: null,
    validator: 'zod (hand-wired)',
    notes: [
      'The Node ceiling: a bare requestListener with a hand-rolled switch, no framework. Routing is a startsWith chain, which is faster than any real router.',
    ],
  },
  {
    id: 'fastify',
    label: 'Fastify (Node)',
    runtime: 'node',
    entry: 'servers/fastify.ts',
    preload: [],
    versionOf: 'fastify',
    validator: 'zod (validatorCompiler)',
    notes: [
      'Given zod through its validatorCompiler hook rather than its default ajv/JSON Schema path, so the validate scenario stays comparable. Ajv compiles to straight-line JS and is materially faster than zod - this understates Fastify on that one scenario.',
      'No response schema is set, so serialisation is JSON.stringify rather than fast-json-stringify, matching every other subject.',
    ],
  },
  {
    id: 'express',
    label: 'Express (Node)',
    runtime: 'node',
    entry: 'servers/express.ts',
    preload: [],
    versionOf: 'express',
    validator: 'zod (hand-wired)',
    notes: ['Express 5 with express.json() for the validate scenario only.'],
  },
  {
    id: 'nethttp',
    label: 'net/http (Go)',
    runtime: 'go',
    entry: 'servers/go/cmd/nethttp/main.go',
    preload: [],
    versionOf: null,
    validator: 'go-playground/validator v10',
    notes: [
      'The Go ceiling, mirroring node:http and bun-serve for their runtimes: the standard library and nothing else.',
      'Routing is http.ServeMux with Go 1.22 method-and-wildcard patterns, so the router is native the same way Bun.serve({ routes }) is.',
      'runtime.GOMAXPROCS(1). Go would otherwise use all 32 cores while every other subject uses one, which measures the machine and not the framework.',
      'Compiled before the run. The startup column times the binary, not `go build`.',
    ],
  },
  {
    id: 'gin',
    label: 'Gin (Go)',
    runtime: 'go',
    entry: 'servers/go/cmd/gin/main.go',
    preload: [],
    versionOf: 'github.com/gin-gonic/gin',
    validator: 'gin binding (go-playground/validator v10)',
    notes: [
      "The Go framework Elysia's landing page compares itself against, which is why it is here.",
      'gin.New(), not gin.Default(): Default installs a per-request logger and a recovery middleware, and nothing else in this suite logs or recovers.',
      'runtime.GOMAXPROCS(1), for the reason on the net/http row.',
      'Compiled before the run. The startup column times the binary, not `go build`.',
    ],
  },
  {
    id: 'axum',
    label: 'Axum (Rust)',
    runtime: 'rust',
    entry: 'servers/rust/src/axum.rs',
    preload: [],
    versionOf: 'axum',
    validator: 'validator crate (derive)',
    notes: [
      'Axum on tokio, hyper underneath, no tower layers.',
      'A single-threaded tokio runtime (flavor = "current_thread"), for the same reason Go is pinned to one core.',
      'Built with a plain `cargo build --release`: no LTO, no codegen-units=1, no profile overrides that nothing else in this suite gets.',
      'Compiled before the run. The startup column times the binary, not `cargo build`.',
    ],
  },
  {
    id: 'spring',
    label: 'Spring Boot (JVM)',
    runtime: 'jvm',
    entry: 'servers/java/src/main/java/bench/App.java',
    preload: [],
    versionOf: 'spring-boot-starter-parent',
    validator: 'jakarta.validation (Hibernate Validator)',
    warmupFloorSeconds: 30,
    notes: [
      'Spring Boot on its default stack: Spring MVC over embedded Tomcat, Jackson, Hibernate Validator. No AOT, no CDS, no native image, no JVM flags.',
      'Warmed for 30 seconds rather than the 3 every other subject gets, because 3 does not warm a JIT and a cold JVM number would be as dishonest as a flattering one.',
      'Tomcat is pinned to one worker thread, for the same reason Go and tokio are pinned to one core.',
      'Packaged before the run. The startup column times `java -jar`, not `mvn package` - and unlike the compiled subjects that startup includes class loading and JIT-free first execution, which is a real cost and not an artefact.',
    ],
  },
  {
    id: 'django',
    label: 'Django (Python)',
    runtime: 'python',
    entry: 'servers/python/app.py',
    preload: [],
    versionOf: 'django',
    validator: 'hand-written checks',
    notes: [
      'Django on `wsgiref.simple_server` from the standard library, one process and one thread, for the same reason Go and tokio are pinned to one core. Not `runserver`, which reloads, threads and logs every request.',
      'DEBUG off and MIDDLEWARE empty: the default stack adds sessions, auth, messages and CSRF, none of which the other subjects carry.',
      "Validation is hand-written rather than DRF. DRF is a separate framework and this row would then measure DRF; Django's own forms validate form-encoded input, not JSON.",
      '**A WSGI server, and that is the honest caveat on this row.** Every other subject here speaks HTTP natively or through an event loop. `wsgiref` is a synchronous reference implementation, not a production server - a real deployment puts gunicorn or uvicorn in front with several workers, which this suite deliberately does not do to anyone.',
      'Interpreted, so there is nothing to compile and no build time to report.',
    ],
  },
];
