import { rm } from 'node:fs/promises';
import { build } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * Builds the dashboard page and writes it into `@dunx/dashboard` as a string
 * constant.
 *
 * Identical in shape to `internal/openapi-ui/scripts/build.ts`, and for the same
 * reasons: the package serves the bundle **inlined** - no `src=`, no `<link>`, no
 * CDN - so the artefact it needs is text rather than a file tree, and committing
 * the generated module keeps `bun test` and `tsc --noEmit` working in a fresh
 * clone with no Vite run and keeps Vite off the publish path.
 *
 * `packages/dashboard`'s own `build` runs this first, so the committed copy cannot
 * go stale.
 */
const HERE = new URL('..', import.meta.url).pathname;
const OUT = `${HERE}dist`;
const TARGET = `${HERE}../../packages/dashboard/src/ui-bundle.ts`;

await rm(OUT, { recursive: true, force: true });

const started = performance.now();

await build({
  root: HERE,
  plugins: [react()],
  logLevel: 'warn',
  build: {
    outDir: OUT,
    emptyOutDir: true,
    minify: 'esbuild',
    cssMinify: true,
    modulePreload: false,
    chunkSizeWarningLimit: 4096,
    reportCompressedSize: false,
    rollupOptions: {
      input: `${HERE}src/main.tsx`,
      output: {
        format: 'iife',
        entryFileNames: 'ui.js',
        assetFileNames: 'ui.[ext]',
        inlineDynamicImports: true,
      },
    },
  },
});

const read = async (name: string): Promise<string> => {
  const file = Bun.file(`${OUT}/${name}`);
  return (await file.exists()) ? file.text() : '';
};

// Vite inlines the CSS into the IIFE for a JS entrypoint, but a config change
// upstream could extract it instead. Either way one string leaves this script.
const css = await read('ui.css');
const js = await read('ui.js');

if (js === '') throw new Error('vite produced no ui.js');

const injected =
  css === ''
    ? ''
    : `(()=>{const s=document.createElement("style");` +
      `s.textContent=${JSON.stringify(css)};document.head.appendChild(s);})();\n`;

/**
 * `</` cannot appear literally inside the `<script>` the page writes. Escaping it
 * is a no-op for JavaScript - `<\/` is `</` in both a string and a regex - and
 * doing it here means `renderShell` pays nothing per request.
 */
const safe = `${injected}${js}`.replaceAll('</', '<\\/');

if (safe.includes('</script')) throw new Error('bundle can close its own tag');

/**
 * The `: string` annotation is load bearing. Without it tsc infers the literal
 * type and `dist/ui-bundle.d.ts` becomes a single-line declaration of the whole
 * minified bundle that every consumer of `@dunx/dashboard/ui` has to parse.
 */
await Bun.write(
  TARGET,
  '// Generated by internal/dashboard-ui - do not edit. Run `bun run build` in\n' +
    '// packages/dashboard, or `bun run bundle` in internal/dashboard-ui.\n' +
    '/** The dashboard page, built by Vite and inlined into the HTML. */\n' +
    `export const UI: string = ${JSON.stringify(safe)};\n`,
);

const bytes = Buffer.byteLength(safe);
console.log(
  `@dunx/dashboard-ui: ${(bytes / 1024).toFixed(1)} KiB ` +
    `(${(Bun.gzipSync(safe).length / 1024).toFixed(1)} KiB gzip), ` +
    `${Math.round(performance.now() - started)}ms -> packages/dashboard/src/ui-bundle.ts`,
);
