import { rm } from 'node:fs/promises';
import { build } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * Builds the explorer and writes it into `@dunx/openapi` as a string constant.
 *
 * The package serves the bundle **inlined** - no `src=`, no `<link>`, no CDN -
 * so the artefact it needs is text, not a file tree. Committing the generated
 * module is what keeps `bun test` and `tsc --noEmit` working in a fresh clone
 * without a Vite run, and keeps Vite off the publish path.
 *
 * Vite rather than `bun build ./index.html`, which is what `tools/docs` uses:
 * every byte here is inlined into a page a backend serves, and Vite's Rollup
 * tree-shaking is worth its 2 s against the ~25 % larger output Bun produced
 * (measured for the docs site, recorded in docs/ARCHITECTURE.md).
 */
const HERE = new URL('..', import.meta.url).pathname;
const OUT = `${HERE}dist`;
const TARGET = `${HERE}../../packages/openapi/src/ui-bundle.ts`;

await rm(OUT, { recursive: true, force: true });

const started = performance.now();

await build({
  root: HERE,
  plugins: [react()],
  logLevel: 'warn',
  build: {
    outDir: OUT,
    emptyOutDir: true,
    minify: 'esbuild',
    cssMinify: true,
    modulePreload: false,
    chunkSizeWarningLimit: 4096,
    reportCompressedSize: false,
    rollupOptions: {
      input: `${HERE}src/main.tsx`,
      output: {
        format: 'iife',
        entryFileNames: 'ui.js',
        assetFileNames: 'ui.[ext]',
        inlineDynamicImports: true,
      },
    },
  },
});

const read = async (name: string): Promise<string> => {
  const file = Bun.file(`${OUT}/${name}`);
  return (await file.exists()) ? file.text() : '';
};

// Vite inlines the CSS into the IIFE for a JS entrypoint, but a config change
// upstream could extract it instead. Either way one string leaves this script.
const css = await read('ui.css');
const js = await read('ui.js');

if (js === '') throw new Error('vite produced no ui.js');

const injected =
  css === ''
    ? ''
    : `(()=>{const s=document.createElement("style");` +
      `s.textContent=${JSON.stringify(css)};document.head.appendChild(s);})();\n`;

/**
 * `</` cannot appear literally inside the `<script>` the page writes. Escaping it
 * is a no-op for JavaScript - `<\/` is `</` in both a string and a regex - and
 * doing it here means `renderPage` pays nothing per request.
 */
const safe = `${injected}${js}`.replaceAll('</', '<\\/');

if (safe.includes('</script')) throw new Error('bundle can close its own tag');

/**
 * The `: string` annotation is load bearing. Without it tsc infers the literal
 * type and `dist/ui-bundle.d.ts` becomes a 456 KB single-line declaration that
 * every consumer of `@dunx/openapi/ui` has to parse. Widening it collapses that
 * file to one line, and nothing wants the literal type of a minified bundle.
 */
await Bun.write(
  TARGET,
  '// Generated by tools/openapi-ui - do not edit. Run `bun run build` in\n' +
    '// packages/openapi, or `bun run bundle` in tools/openapi-ui.\n' +
    '/** The API explorer, built by Vite and inlined into the page. */\n' +
    `export const UI: string = ${JSON.stringify(safe)};\n`,
);

const bytes = Buffer.byteLength(safe);
console.log(
  `@dunx/openapi-ui: ${(bytes / 1024).toFixed(1)} KiB ` +
    `(${(Bun.gzipSync(safe).length / 1024).toFixed(1)} KiB gzip), ` +
    `${Math.round(performance.now() - started)}ms -> packages/openapi/src/ui-bundle.ts`,
);
