import { LOGO_FAVICON } from '../src/logo.js';

/**
 * Writes the one copy of the mark a published package can import. `@dunx/http`
 * cannot depend on this workspace, and this one cannot import `@dunx/http` for
 * the browser bundles without taking the server along, so the geometry stays
 * here and the icon is emitted there.
 *
 * `: string` keeps `dist/internal.d.ts` from declaring the whole URI as a type.
 */
const TARGET = new URL('../../../packages/http/src/logo.ts', import.meta.url);

await Bun.write(
  TARGET,
  '// Generated by internal/ui - do not edit. Run `bun run gen:logo` in internal/ui.\n' +
    '/** The dunx mark as a data: URI, for the rel=icon of a page a backend serves. */\n' +
    `export const LOGO_FAVICON: string = ${JSON.stringify(LOGO_FAVICON)};\n`,
);
