/**
 * Writes `tools/mcp/src/generated.ts`: the written guide, the smallest working app,
 * and the catalogue `bunx @dunx/create-app` scaffolds from.
 *
 * `@dunx/mcp` answers adoption questions before there is an app to read, so the
 * answers have to travel inside the published package - `docs/guide/` and
 * `examples/minimal/` are outside it and `files` cannot reach them. Committed
 * rather than generated at publish time, and regenerated by that package's own
 * `build`, so a source checkout works with no build step and a diff shows what a
 * consumer receives. Same arrangement as `packages/dashboard/src/ui-bundle.ts`.
 *
 * Every input is something CI already builds, boots or tours, so nothing here can
 * describe a template that stopped working.
 */
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FEATURES } from '../tools/create-app/src/features.js';
import type { GuideDoc } from '../tools/mcp/src/guide.js';
import type {
  ScaffoldFeature,
  Starter,
  StarterFile,
} from '../tools/mcp/src/scaffold.js';

// `fileURLToPath` rather than `.pathname`, which leaves a space as `%20` and
// makes every read below fail on a checkout path that has one.
const ROOT = fileURLToPath(new URL('..', import.meta.url));
const BLOB = 'https://github.com/petarzarkov/dunx/blob/main';
const OUT = join(ROOT, 'tools/mcp/src/generated.ts');

/**
 * A chapter link becomes its resource URI, so a client following one stays in the
 * corpus. Everything else is a repo path the consumer does not have, so it becomes
 * an absolute link. `../../` is replaced before `../`, or the second pattern eats
 * the first half of the first.
 */
const rewriteLinks = (markdown: string): string =>
  markdown
    .replace(/\]\(\.\/(\d+[a-z0-9-]*)\.md/gi, '](dunx://guide/$1')
    .replace(/\]\(\.\.\/\.\.\//g, `](${BLOB}/`)
    .replace(/\]\(\.\.\//g, `](${BLOB}/docs/`);

/** The first paragraph after the `#` heading, which is what the index shows. */
const summarize = (lines: readonly string[]): string => {
  const start = lines.findIndex((line) => line.startsWith('# '));
  // No heading means no summary. Reading from line 0 instead took the badge row.
  if (start === -1) return '';
  const paragraph: string[] = [];

  for (const line of lines.slice(start + 1)) {
    const trimmed = line.trim();
    if (trimmed === '') {
      if (paragraph.length > 0) break;
      continue;
    }
    if (trimmed.startsWith('#') || trimmed.startsWith('```')) break;
    paragraph.push(trimmed);
  }

  return paragraph.join(' ');
};

const readGuide = async (): Promise<readonly GuideDoc[]> => {
  const dir = join(ROOT, 'docs/guide');
  const slugs: string[] = [];
  for await (const file of new Bun.Glob('*.md').scan({ cwd: dir })) {
    slugs.push(file.replace(/\.md$/, ''));
  }
  slugs.sort();

  const docs: GuideDoc[] = [];
  for (const slug of slugs) {
    const body = rewriteLinks(await Bun.file(join(dir, `${slug}.md`)).text());
    const lines = body.split('\n');
    docs.push({
      slug,
      title:
        lines
          .find((line) => line.startsWith('# '))
          ?.slice(2)
          .trim() ?? slug,
      summary: summarize(lines),
      sections: lines
        .filter((line) => line.startsWith('## '))
        .map((line) => line.slice(3).trim()),
      body,
    });
  }
  return docs;
};

/**
 * `examples/minimal/src` plus the base template's `bunfig.toml` and
 * `tsconfig.json`, which together are exactly what `bunx @dunx/create-app` writes
 * for an empty selection. The example is booted and tested in CI; the base files
 * are what a generated app receives.
 */
const readStarter = async (): Promise<Starter> => {
  const files: StarterFile[] = [];

  const src = join(ROOT, 'examples/minimal/src');
  const names: string[] = [];
  for await (const file of new Bun.Glob('*.ts').scan({ cwd: src })) {
    names.push(file);
  }
  for (const name of names.sort()) {
    files.push({
      path: `src/${name}`,
      body: await Bun.file(join(src, name)).text(),
    });
  }

  const base = join(ROOT, 'tools/create-app/templates/base');
  files.push({
    path: 'bunfig.toml',
    body: await Bun.file(join(base, '_bunfig.toml')).text(),
  });
  files.push({
    path: 'tsconfig.json',
    body: await Bun.file(join(base, 'tsconfig.json')).text(),
  });

  const manifest = (await Bun.file(
    join(ROOT, 'examples/minimal/package.json'),
  ).json()) as {
    dependencies?: Record<string, string>;
    devDependencies?: Record<string, string>;
  };
  const engines = (await Bun.file(
    join(ROOT, 'tools/mcp/package.json'),
  ).json()) as {
    engines?: Record<string, string>;
  };

  return {
    runtime: `bun ${engines.engines?.['bun'] ?? '>=1.4.1'}`,
    dependencies: Object.keys(manifest.dependencies ?? {}),
    devDependencies: Object.keys(manifest.devDependencies ?? {}),
    files,
  };
};

const readScaffold = (): readonly ScaffoldFeature[] =>
  FEATURES.map((feature) => ({
    name: feature.name,
    summary: feature.summary,
    requires: feature.requires,
    dependencies: feature.dependencies,
    // Spread rather than assigned, so an absent service stays an absent key:
    // `exactOptionalPropertyTypes` rejects `service: undefined`.
    ...(feature.service === undefined ? {} : { service: feature.service }),
  }));

/**
 * `JSON.parse` of one string literal rather than an object literal spanning ten
 * thousand lines: it keeps the file at thirteen lines, which is what keeps `max-lines`
 * and `oxfmt` from having an opinion about generated data. Bun parses the whole
 * corpus in under a millisecond.
 */
const literal = (value: unknown): string =>
  JSON.stringify(JSON.stringify(value));

/**
 * Exported so `gen-mcp-corpus.test.ts` can re-render and compare, which is what
 * catches a committed corpus that a guide edit left behind. `gen:readme --check`
 * exists because nothing ran it and it silently broke; this is the same guard.
 */
export const renderCorpus = async (): Promise<string> => {
  const guide = await readGuide();
  const starter = await readStarter();
  const scaffold = readScaffold();

  return `// Generated by scripts/gen-mcp-corpus.ts - do not edit. Run \`bun run build\` in
// tools/mcp, or \`bun run gen:mcp\` from the repo root.
import type { GuideDoc } from './guide.js';
import type { ScaffoldFeature, Starter } from './scaffold.js';

/** Every chapter of \`docs/guide\`, with chapter links rewritten to \`dunx://guide/\`. */
export const GUIDE = JSON.parse(${literal(guide)}) as readonly GuideDoc[];

/** \`examples/minimal\` plus the base template, which is what an empty selection writes. */
export const MINIMAL = JSON.parse(${literal(starter)}) as Starter;

/** The features \`bunx @dunx/create-app\` composes an app from. */
export const SCAFFOLD = JSON.parse(${literal(scaffold)}) as readonly ScaffoldFeature[];
`;
};

export const CORPUS_PATH = OUT;

if (import.meta.main) {
  const rendered = await renderCorpus();
  await Bun.write(OUT, rendered);
  console.log(
    `tools/mcp/src/generated.ts  ${(rendered.length / 1024).toFixed(1)} KB`,
  );
}
