import { describe, expect, it } from 'bun:test';
import { $ } from 'bun';

/**
 * Enforces the CLAUDE.md rule banning em and en dashes. oxlint cannot do this:
 * the characters turn up in prose, Markdown and generated JSON far more often
 * than in code, and a linter that only reads TypeScript would miss almost all of
 * them.
 *
 * Written as escapes rather than literals so this file does not match itself.
 */
const EM = '\u2014';
const EN = '\u2013';

const ALLOWED = new Set([
  // Has to name the characters it bans.
  'CLAUDE.md',
  // Generated, minified, and mostly third party: the one dash in here is inside
  // a Mantine error string. Already exempt from lint and format for the same
  // reason. Regenerated by `packages/openapi`'s build, so editing it is pointless.
  'packages/openapi/src/ui-bundle.ts',
]);

const BINARY = new Set(['.png', '.jpg', '.jpeg', '.gif', '.ico', '.webp']);

describe('no em or en dashes', () => {
  it('across every tracked file', async () => {
    const listed = await $`git ls-files`.text();
    const offenders: string[] = [];

    for (const file of listed.split('\n').filter(Boolean)) {
      if (ALLOWED.has(file)) continue;
      if (BINARY.has(file.slice(file.lastIndexOf('.')))) continue;

      const text = await Bun.file(file)
        .text()
        .catch(() => '');
      const line = text
        .split('\n')
        .findIndex((row) => row.includes(EM) || row.includes(EN));
      if (line !== -1) offenders.push(`${file}:${line + 1}`);
    }

    expect(offenders).toEqual([]);
  });
});
