import { describe, expect, it } from 'bun:test';
import { $ } from 'bun';

/**
 * Enforces the CLAUDE.md rule banning em and en dashes. oxlint cannot do this:
 * the characters turn up in prose, Markdown and generated JSON far more often
 * than in code, and a linter that only reads TypeScript would miss almost all of
 * them.
 *
 * Written as escapes rather than literals so this file does not match itself.
 */
const EM = '\u2014';
const EN = '\u2013';

const ALLOWED = new Set([
  // Has to name the characters it bans.
  'CLAUDE.md',
  // Generated, minified, and mostly third party: the dashes in these are inside
  // Mantine error strings. Already exempt from lint and format for the same
  // reason, and each is regenerated by its package's build, so editing one is
  // pointless.
  'packages/openapi/src/ui-bundle.ts',
  'packages/dashboard/src/ui-bundle.ts',
]);

const BINARY = new Set(['.png', '.jpg', '.jpeg', '.gif', '.ico', '.webp']);

describe('no em or en dashes', () => {
  it('across every tracked and untracked file', async () => {
    // `git ls-files` alone misses untracked files, so a green run on brand-new
    // work meant nothing until it was staged. `--others --exclude-standard` adds
    // everything git can see that is not ignored, which is what a new guide page
    // is before anyone stages it.
    const listed =
      await $`git ls-files --cached --others --exclude-standard`.text();
    const offenders: string[] = [];

    for (const file of listed.split('\n').filter(Boolean)) {
      if (ALLOWED.has(file)) continue;
      if (BINARY.has(file.slice(file.lastIndexOf('.')))) continue;

      const text = await Bun.file(file)
        .text()
        .catch(() => '');
      const line = text
        .split('\n')
        .findIndex((row) => row.includes(EM) || row.includes(EN));
      if (line !== -1) offenders.push(`${file}:${line + 1}`);
    }

    expect(offenders).toEqual([]);
  });
});
