/**
 * The screenshot mechanics behind every social card in the repo.
 *
 * `internal/docs` drew the first one and owned all of this. A second card for
 * `examples/full` would have been a second copy of the `Bun.WebView` dance, so
 * the mechanism moved here and each site keeps only the words it says. Root
 * `scripts/` is where a generator two workspaces need already lives -
 * `positioning.ts` is imported from `internal/docs` by relative path the same
 * way.
 *
 * `Bun.Image` cannot do this: it decodes JPEG, PNG, WebP, GIF, BMP, TIFF, HEIC
 * and AVIF, and an SVG handed to it fails `ERR_IMAGE_UNKNOWN_FORMAT` (probed on
 * Bun 1.4.2). So a card is HTML screenshotted through the `Bun.WebView` the
 * `browser` phase already drives, which needs no new dependency and no
 * rasteriser.
 *
 * Cards are committed rather than generated by a build, for the reason the
 * coverage badges are: a deploy job would otherwise need a Chrome, and the words
 * change a few times a year.
 */

import { writeFileSync } from 'node:fs';

/** The declared `og:image:width`/`height`, so a card cannot disagree with its tags. */
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

/** The logo mark's own stops, so every card's accent is the wordmark's accent. */
export const OG_CYAN = '#22b8cf';
export const OG_INDIGO = '#4c6ef5';
export const OG_VIOLET = '#7950f2';

/**
 * The mark, at card scale. The geometry is `internal/ui/src/logo.ts`'s; a root
 * script cannot import a private workspace, so it is restated here once and read
 * by both generators rather than by neither.
 */
export const ogLogo = (size = 64): string =>
  `<svg viewBox="0 0 32 32" width="${size}" height="${size}" fill="none" aria-hidden="true">
  <linearGradient id="c" x1="4" y1="4" x2="28" y2="28" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="${OG_CYAN}" />
    <stop offset=".5" stop-color="${OG_INDIGO}" />
    <stop offset="1" stop-color="${OG_VIOLET}" />
  </linearGradient>
  <g stroke="url(#c)" stroke-width="4" stroke-linecap="round">
    <path d="M5.9 5.6H15.7a10.4 10.4 0 0 1 0 20.8H5.9" />
    <path d="m9.7 11.4 9.2 9.2m0-9.2-9.2 9.2" />
  </g>
</svg>`;

/**
 * The paint. Two cards differ in colour and copy and in nothing else, so this is
 * what each one supplies instead of a second stylesheet.
 */
export interface CardStyle {
  /** The layered background, as one `background` value. */
  readonly background: string;
  readonly ink: string;
  readonly dim: string;
  /** The gradient the second headline line is cut out of. */
  readonly accent: string;
  /** Border and text for the first chip, which reads as the primary one. */
  readonly chipAccent: string;
  readonly chipInk: string;
}

/**
 * The words. Every field is inserted verbatim, so a caller passing anything but
 * a literal escapes it first - `internal/docs` runs `positioning.ts` through its
 * own `escapeHtml`, and the demo card is literals throughout.
 */
export interface CardContent {
  /** A pill beside the wordmark. The site's card has none. */
  readonly badge?: string;
  /** Two lines: the second is set in `style.accent`. */
  readonly headline: readonly [string, string];
  readonly blurb: string;
  readonly chips: readonly string[];
}

/**
 * The shell both cards render through.
 *
 * `scripts/og-card.ts` was meant to be the shared half and only held the
 * screenshot: the 50-line stylesheet stayed duplicated in both generators, so
 * the lattice, the layout classes and the chip rules were two copies to keep in
 * step. The sizes are one set now rather than two that drifted by 4px.
 */
export const cardHtml = (style: CardStyle, content: CardContent): string =>
  `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  html, body { width: ${OG_WIDTH}px; height: ${OG_HEIGHT}px; }
  body {
    position: relative;
    overflow: hidden;
    background: ${style.background};
    color: ${style.ink};
    font-family: 'Inter', 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
  }
  /* A 54px lattice, faded out towards the bottom so the chips sit on flat ink. */
  .grid {
    position: absolute; inset: 0;
    background-image:
      linear-gradient(to right, rgba(148, 163, 184, 0.10) 1px, transparent 1px),
      linear-gradient(to bottom, rgba(148, 163, 184, 0.10) 1px, transparent 1px);
    background-size: 54px 54px;
    mask-image: radial-gradient(120% 100% at 50% 0%, #000 35%, transparent 78%);
  }
  /* space-between rather than a pair of auto margins, which fought each other
     and pushed the chips off the 630px canvas. */
  .card {
    position: relative; height: 100%; padding: 56px 68px;
    display: flex; flex-direction: column; justify-content: space-between;
  }
  .brand { display: flex; align-items: center; gap: 16px; }
  .brand span { font-size: 46px; font-weight: 700; letter-spacing: -0.02em; }
  .badge {
    margin-left: 10px; padding: 7px 16px; border-radius: 999px;
    font: 600 19px ui-monospace, 'SFMono-Regular', Menlo, monospace;
    color: ${style.chipAccent}; border: 1px solid ${style.chipAccent};
    background: rgba(148, 163, 184, 0.08);
  }
  h1 { font-size: 58px; line-height: 1.1; font-weight: 800; letter-spacing: -0.03em; }
  .accent {
    background-image: ${style.accent};
    -webkit-background-clip: text; background-clip: text; color: transparent;
  }
  p { margin-top: 20px; font-size: 24px; line-height: 1.45; color: ${style.dim}; max-width: 53ch; }
  p b { color: ${style.ink}; font-weight: 600; }
  .chips { display: flex; gap: 12px; }
  .chip {
    padding: 9px 18px; border-radius: 9px; font-size: 21px;
    border: 1px solid rgba(148, 163, 184, 0.28); color: ${style.chipInk};
    font-family: ui-monospace, 'SFMono-Regular', Menlo, monospace;
  }
  .chip:first-child { border-color: ${style.chipAccent}; color: ${style.chipAccent}; }
</style>
</head>
<body>
  <div class="grid"></div>
  <div class="card">
    <div class="brand">${ogLogo()}<span>dunx</span>${
      content.badge === undefined
        ? ''
        : `<span class="badge">${content.badge}</span>`
    }</div>
    <div>
      <h1>${content.headline[0]}<br /><span class="accent">${content.headline[1]}</span></h1>
      <p>${content.blurb}</p>
    </div>
    <div class="chips">
      ${content.chips.map((chip) => `<span class="chip">${chip}</span>`).join('')}
    </div>
  </div>
</body>
</html>
`;

/**
 * Serve `html` to a headless Chrome, shoot it at exactly the declared size, and
 * write the PNG. Returns the byte length so a caller can print it.
 */
export const renderCard = async (
  target: string,
  html: string,
): Promise<number> => {
  const server = Bun.serve({
    port: 0,
    fetch: () =>
      new Response(html, { headers: { 'content-type': 'text/html' } }),
  });

  const view = new Bun.WebView({ width: OG_WIDTH, height: OG_HEIGHT });
  try {
    // `cdp()` has no session until something has been navigated to, so the
    // order is fixed: navigate, then override, then let the resize repaint.
    await view.navigate(server.url.origin);
    // A retina capture would be sharper and would then disagree with the tags,
    // and the unfurlers scale to their own slot anyway.
    await view.cdp('Emulation.setDeviceMetricsOverride', {
      width: OG_WIDTH,
      height: OG_HEIGHT,
      deviceScaleFactor: 1,
      mobile: false,
    });
    // Gradient text and masks settle a frame after layout, the same wait
    // `preview.ts` takes before a shot.
    await Bun.sleep(400);

    const bytes = new Uint8Array(await (await view.screenshot()).arrayBuffer());
    writeFileSync(target, bytes);
    return bytes.byteLength;
  } finally {
    view.close();
    await server.stop(true);
  }
};

/** What every generator prints, so two of them cannot describe a card differently. */
export const reportCard = (label: string, bytes: number): void => {
  console.log(
    `${label}: ${OG_WIDTH}x${OG_HEIGHT}, ${(bytes / 1024).toFixed(1)} KB`,
  );
};
