/**
 * The screenshot mechanics behind every social card in the repo.
 *
 * `internal/docs` drew the first one and owned all of this. A second card for
 * `examples/full` would have been a second copy of the `Bun.WebView` dance, so
 * the mechanism moved here and each site keeps only the words it says. Root
 * `scripts/` is where a generator two workspaces need already lives -
 * `positioning.ts` is imported from `internal/docs` by relative path the same
 * way.
 *
 * `Bun.Image` cannot do this: it decodes JPEG, PNG, WebP, GIF, BMP, TIFF, HEIC
 * and AVIF, and an SVG handed to it fails `ERR_IMAGE_UNKNOWN_FORMAT` (probed on
 * Bun 1.4.2). So a card is HTML screenshotted through the `Bun.WebView` the
 * `browser` phase already drives, which needs no new dependency and no
 * rasteriser.
 *
 * Cards are committed rather than generated by a build, for the reason the
 * coverage badges are: a deploy job would otherwise need a Chrome, and the words
 * change a few times a year.
 */

import { writeFileSync } from 'node:fs';

/** The declared `og:image:width`/`height`, so a card cannot disagree with its tags. */
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

/** The logo mark's own stops, so every card's accent is the wordmark's accent. */
export const OG_CYAN = '#22b8cf';
export const OG_INDIGO = '#4c6ef5';
export const OG_VIOLET = '#7950f2';

/**
 * The mark, at card scale. The geometry is `internal/ui/src/logo.ts`'s; a root
 * script cannot import a private workspace, so it is restated here once and read
 * by both generators rather than by neither.
 */
export const ogLogo = (size = 64): string =>
  `<svg viewBox="0 0 32 32" width="${size}" height="${size}" fill="none" aria-hidden="true">
  <linearGradient id="c" x1="4" y1="4" x2="28" y2="28" gradientUnits="userSpaceOnUse">
    <stop offset="0" stop-color="${OG_CYAN}" />
    <stop offset=".5" stop-color="${OG_INDIGO}" />
    <stop offset="1" stop-color="${OG_VIOLET}" />
  </linearGradient>
  <g stroke="url(#c)" stroke-width="4" stroke-linecap="round">
    <path d="M5.9 5.6H15.7a10.4 10.4 0 0 1 0 20.8H5.9" />
    <path d="m9.7 11.4 9.2 9.2m0-9.2-9.2 9.2" />
  </g>
</svg>`;

/**
 * Serve `html` to a headless Chrome, shoot it at exactly the declared size, and
 * write the PNG. Returns the byte length so a caller can print it.
 */
export const renderCard = async (
  target: string,
  html: string,
): Promise<number> => {
  const server = Bun.serve({
    port: 0,
    fetch: () =>
      new Response(html, { headers: { 'content-type': 'text/html' } }),
  });

  const view = new Bun.WebView({ width: OG_WIDTH, height: OG_HEIGHT });
  try {
    // `cdp()` has no session until something has been navigated to, so the
    // order is fixed: navigate, then override, then let the resize repaint.
    await view.navigate(server.url.origin);
    // A retina capture would be sharper and would then disagree with the tags,
    // and the unfurlers scale to their own slot anyway.
    await view.cdp('Emulation.setDeviceMetricsOverride', {
      width: OG_WIDTH,
      height: OG_HEIGHT,
      deviceScaleFactor: 1,
      mobile: false,
    });
    // Gradient text and masks settle a frame after layout, the same wait
    // `preview.ts` takes before a shot.
    await Bun.sleep(400);

    const bytes = new Uint8Array(await (await view.screenshot()).arrayBuffer());
    writeFileSync(target, bytes);
    return bytes.byteLength;
  } finally {
    view.close();
    await server.stop(true);
  }
};

/** What every generator prints, so two of them cannot describe a card differently. */
export const reportCard = (label: string, bytes: number): void => {
  console.log(
    `${label}: ${OG_WIDTH}x${OG_HEIGHT}, ${(bytes / 1024).toFixed(1)} KB`,
  );
};
