import { afterEach, describe, expect, test } from 'bun:test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { scaffold, ScaffoldError } from './scaffold.js';

const dirs: string[] = [];

const workspace = (): string => {
  const dir = mkdtempSync(join(tmpdir(), 'dunx-compose-'));
  dirs.push(dir);
  return dir;
};

afterEach(() => {
  for (const dir of dirs.splice(0))
    rmSync(dir, { recursive: true, force: true });
});

const compose = async (features: readonly string[]) => {
  const cwd = workspace();
  const result = await scaffold({
    target: 'app',
    cwd,
    features,
    version: '^9.9.9',
  });
  const read = (path: string): Promise<string> =>
    Bun.file(join(result.directory, path)).text();
  return { result, read };
};

describe('a composed app', () => {
  test('stays on the minimal template when no feature is asked for', async () => {
    const { result } = await compose([]);
    expect(result.template).toBe('minimal');
    expect(result.features).toEqual([]);
    expect(result.files).toContain('src/greetings.controller.ts');
  });

  test('copies each feature directory and generates the wiring', async () => {
    const { result, read } = await compose(['notes']);

    expect(result.template).toBe('composed');
    expect(result.features).toEqual(['notes']);
    // The feature's own files, verbatim.
    expect(result.files).toContain('src/notes/notes.controller.ts');
    // The four files the full example states every feature at once in.
    for (const generatedFile of [
      'src/main.ts',
      'src/bootstrap.ts',
      'src/app.module.ts',
      'src/config.ts',
    ]) {
      expect(result.files).toContain(generatedFile);
      expect(await read(generatedFile)).toContain(
        'Generated by @dunx/create-app',
      );
    }
    // No greetings: that is the fixed template's, not a feature.
    expect(result.files).not.toContain('src/greetings.controller.ts');
  });

  test('imports exactly the modules it resolved, in that order', async () => {
    const { result, read } = await compose(['users', 'notes']);
    expect(result.features).toEqual(['notes', 'database', 'users']);

    const module = await read('src/app.module.ts');
    expect(module).toContain(
      "import { NotesModule } from './notes/notes.module.js';",
    );
    expect(module).toContain(
      "import { DatabaseModule } from './database/database.module.js';",
    );
    // Construction order: the database before the feature that reads it.
    expect(module.indexOf('DatabaseModule,')).toBeLessThan(
      module.indexOf('UsersModule,'),
    );
    expect(module).not.toContain('ChatModule');
  });

  test('contributes only the config groups its features read', async () => {
    const { read } = await compose(['cache']);
    const config = await read('src/config.ts');

    expect(config).toContain('REDIS_URL');
    // Base groups are always there: the port and the logger need them.
    expect(config).toContain('PORT');
    expect(config).toContain('LOG_LEVEL');
    // Nothing selected reads these.
    expect(config).not.toContain('DATABASE_FILE');
    expect(config).not.toContain('AUTH_SECRET');
    expect(config).not.toContain('IMAGE_QUALITY');
  });

  test('writes an env example covering the groups it generated', async () => {
    const { read } = await compose(['database']);
    const env = await read('.env.example');
    expect(env).toContain('DATABASE_FILE=:memory:');
    expect(env).toContain('PORT=3000');
    expect(env).not.toContain('REDIS_URL');
  });

  test('adds a dependency per feature and resolves the dunx version', async () => {
    const { read } = await compose(['auth']);
    const manifest = JSON.parse(await read('package.json')) as {
      dependencies: Record<string, string>;
      scripts: Record<string, string>;
    };

    expect(manifest.dependencies['@dunx/auth']).toBe('^9.9.9');
    expect(manifest.dependencies['better-auth']).toMatch(/^\^\d/);
    expect(manifest.dependencies['drizzle-orm']).toMatch(/^\^\d/);
    // Not selected, so not installed.
    expect(manifest.dependencies['bullmq']).toBeUndefined();
    expect(manifest.scripts['worker']).toBeUndefined();
  });

  /** A queue needs a process to drain it, and it is not the web one. */
  test('adds a worker entry point only for jobs', async () => {
    const { result, read } = await compose(['jobs']);
    expect(result.files).toContain('src/worker.ts');
    const manifest = JSON.parse(await read('package.json')) as {
      scripts: Record<string, string>;
    };
    expect(manifest.scripts['worker']).toBe('bun src/worker.ts');
  });

  test('sets the global prefix the copied controllers assume', async () => {
    const { read } = await compose(['notes']);
    expect(await read('src/bootstrap.ts')).toContain(
      "app.setGlobalPrefix('api')",
    );
  });

  test('wraps the root in OpenApiModule only when openapi is selected', async () => {
    expect(
      await (await compose(['openapi'])).read('src/bootstrap.ts'),
    ).toContain('OpenApiModule.forRoot(');
    expect(
      await (await compose(['notes'])).read('src/bootstrap.ts'),
    ).not.toContain('OpenApiModule');
  });

  /**
   * The module alone serves nothing - the board is a global middleware, so a scaffold
   * that imports it without registering it would look wired and answer 404.
   */
  test('registers the dashboard middleware when dashboard is selected', async () => {
    const withBoard = await (
      await compose(['dashboard'])
    ).read('src/bootstrap.ts');
    expect(withBoard).toContain(
      "import { QueueDashboardMiddleware } from '@dunx/queue-dashboard'",
    );
    expect(withBoard).toContain('app.use(QueueDashboardMiddleware)');

    expect(
      await (await compose(['notes'])).read('src/bootstrap.ts'),
    ).not.toContain('QueueDashboardMiddleware');
  });

  test('installs the websocket relay only when websockets are selected', async () => {
    const withWs = await (
      await compose(['websockets'])
    ).read('src/bootstrap.ts');
    expect(withWs).toContain('RedisRelay');
    expect(withWs).toContain('relayChannel: RELAY_CHANNEL');
    expect(
      await (await compose(['notes'])).read('src/bootstrap.ts'),
    ).not.toContain('RedisRelay');
  });

  test('substitutes the app name everywhere, generated or copied', async () => {
    const cwd = workspace();
    const result = await scaffold({
      target: 'app',
      cwd,
      name: 'my-service',
      features: ['websockets'],
      version: '^9.9.9',
    });

    for (const file of result.files) {
      const contents = await Bun.file(join(result.directory, file)).text();
      expect(contents).not.toContain('__DUNX_APP_NAME__');
      expect(contents).not.toContain('__DUNX_VERSION__');
    }
    expect(
      await Bun.file(join(result.directory, 'src/config.ts')).text(),
    ).toContain("'my-service:ws'");
  });

  test('names the real features when asked for one that does not exist', async () => {
    const cwd = workspace();
    await expect(
      scaffold({ target: 'app', cwd, features: ['postgres'] }),
    ).rejects.toThrow(ScaffoldError);
    // And writes nothing: resolution happens before the first file.
    await expect(
      scaffold({ target: 'app', cwd, features: ['postgres'] }),
    ).rejects.toThrow(/Unknown feature/);
  });

  test('carries the base tsconfig and transform preload into every composition', async () => {
    const { result, read } = await compose(['notes']);
    expect(result.files).toContain('bunfig.toml');
    expect(result.files).toContain('tsconfig.json');
    expect(result.files).toContain('.gitignore');
    expect(await read('bunfig.toml')).toContain('@dunx/transform/preload');
  });

  test('lists the features and the services they need in the README', async () => {
    const { read } = await compose(['jobs']);
    const readme = await read('README.md');
    expect(readme).toContain('**jobs**');
    expect(readme).toContain('**images**');
    expect(readme).toContain('Redis or Valkey');
  });
});
