import { describe, expect, it } from 'bun:test';

/**
 * The supported surface, frozen. `@dunx/http` had grown to 173 barrel exports,
 * every one of them a semver promise, and about a third were the framework's own
 * plumbing. Those live in `@dunx/http/internal` now.
 *
 * Freezing the list is what makes an addition show up in a diff, the same way
 * `site.test.tsx` freezes the published documentation set.
 */
const supported = (text: string): readonly string[] => {
  return [
    ...new Set(
      [...text.matchAll(/^export (?:type )?\{([^}]*)\}/gms)]
        .flatMap((match) => (match[1] ?? '').split(','))
        .map((name) => name.trim().replace(/^type /, ''))
        .filter(Boolean),
    ),
  ].sort();
};

const BARREL = [
  'ApiHidden',
  'AppSettings',
  'Authorize',
  'AuthorizeDecision',
  'ClientAddress',
  'Compression',
  'CompressionEncoding',
  'CompressionModule',
  'CompressionOptions',
  'CompressionOptionsInit',
  'Controller',
  'CorsOptions',
  'CorsOrigin',
  'CsrfOptions',
  'DEFAULT_RELAY_CHANNEL',
  'AmqpIndicator',
  'DatabaseIndicator',
  'DefaultHttpOptions',
  'Delete',
  'DiskIndicator',
  'DiskOptions',
  'DiskOptionsInit',
  'Envelope',
  'ErrorFilter',
  'ErrorHandler',
  'ErrorMapper',
  'Gateway',
  'Get',
  'HEALTH_REPORT_SCHEMA',
  'HIDDEN',
  'HeaderPairs',
  'HealthCheckReport',
  'HealthController',
  'HealthIndicator',
  'HealthModule',
  'HealthOptions',
  'HealthOptionsInit',
  'HealthRegistry',
  'HealthReport',
  'HttpApp',
  'HttpError',
  'HttpErrorOptions',
  'HttpFactory',
  'HttpMethod',
  'HttpOptions',
  'HttpOptionsProvider',
  'HttpStatusCode',
  'HttpStatusName',
  'IDEMPOTENCY_KEY_HEADER',
  'IDEMPOTENCY_KEY_PATTERN',
  'IDEMPOTENT',
  'IDEMPOTENT_REPLAYED_HEADER',
  'Idempotent',
  'IdempotentRoute',
  'IdempotencyClaim',
  'IdempotencyGuard',
  'IdempotencyModule',
  'IdempotencyOptions',
  'IdempotencyOptionsInit',
  'IdempotencyRecord',
  'IdempotencyRedis',
  'IdempotencyStore',
  'MemoryIdempotencyStore',
  'RedisIdempotencyStore',
  'StoredResponse',
  'InferOutput',
  'Input',
  'InputSource',
  'inlineScriptPolicy',
  'setAbsentHeaders',
  'JsonSchema',
  'MemoryIndicator',
  'MemoryOptions',
  'MemoryOptionsInit',
  'MemoryThrottleStore',
  'MetaKey',
  'MetaRecord',
  'Middleware',
  'Next',
  'OnClose',
  'OnDrain',
  'OnMessage',
  'OnOpen',
  'OnPing',
  'OnPong',
  'OnUpgrade',
  'PUBLIC',
  'Patch',
  'PingProbe',
  'Post',
  'ProbeResult',
  'ProbeState',
  'PubSub',
  'PubSubRelay',
  'Public',
  'Put',
  'QueryProbe',
  'RoundTripIndicator',
  'ROLES',
  'Readiness',
  'ReadinessOptions',
  'RedisIndicator',
  'RedisRelay',
  'PostgresRelay',
  'WsRelay',
  'RelayConnectionOptions',
  'PostgresRelayConnectionOptions',
  'RedisRelayOptions',
  'PostgresRelayOptions',
  'RedisThrottleStore',
  'RelayOptions',
  'RelayPublisher',
  'RelayPublisherInit',
  'RequestLoggingMiddleware',
  'RequestLoggingOptions',
  'ResponseMap',
  'Returns',
  'Roles',
  'RouteContext',
  'RouteFilter',
  'RouteHandler',
  'RouteInput',
  'RoutePath',
  'RouteSchemas',
  'SKIP_THROTTLE',
  'STRICT_CSP',
  'SecurityHeadersOptions',
  'SkipThrottle',
  'Socket',
  'SocketContext',
  'SocketData',
  'SocketDispatch',
  'SocketErrorHandler',
  'SocketFrame',
  'SocketLoggingMiddleware',
  'SocketLoggingOptions',
  'SocketMiddleware',
  'SocketNext',
  'SocketObserver',
  'SocketOptions',
  'SocketOutcome',
  'Sse',
  'SseEvent',
  'SseInput',
  'SseResult',
  'SseSchemas',
  'SseStream',
  'SseStreamOptions',
  'StandardSchemaIssue',
  'StandardSchemaResult',
  'StandardSchemaV1',
  'StaticFiles',
  'StaticModule',
  'StaticOptions',
  'StorageIndicator',
  'StorageProbe',
  'StorageProbeOptions',
  'StorageProbeOptionsInit',
  'StaticOptionsInit',
  'THROTTLE',
  'HttpStatsReport',
  'MetricsMiddleware',
  'RequestMetrics',
  'RouteStats',
  'UNMATCHED_ROUTE',
  'TRACEPARENT_HEADER',
  'TRACERESPONSE_HEADER',
  'TRACESTATE_HEADER',
  'Throttle',
  'ThrottleGuard',
  'ThrottleLimit',
  'ThrottleModule',
  'ThrottleOptions',
  'ThrottleOptionsInit',
  'ThrottleRedis',
  'ThrottleStore',
  'Trace',
  'TraceContext',
  'STREAMS',
  'UNMATCHED',
  'UseGuards',
  'ValidationError',
  'ValidationIssue',
  'defaultErrorMapper',
  'errorMapper',
  'gate',
  'mergeMeta',
  'meta',
  'metaKey',
  'metaOf',
  'WsRelayModule',
].sort();

const CLIENT = [
  'BackoffOptions',
  'FetchError',
  'FetchTransportError',
  'HeaderFactory',
  'ClientTarget',
  'HttpClientOptions',
  'HttpClientOptionsInit',
  'HttpModule',
  'HttpRetryClassifier',
  'HttpRetryOptions',
  'HttpService',
  'RequestConfig',
  'RequestMethod',
  'RetryOptions',
  'SseMessage',
  'httpClient',
].sort();

describe('public surface', () => {
  it('exports exactly the supported set from the barrel', async () => {
    const text = await Bun.file(
      new URL('./index.ts', import.meta.url).pathname,
    ).text();
    expect(supported(text)).toEqual(BARREL);
  });

  it('exports exactly the supported set from ./client', async () => {
    const text = await Bun.file(
      new URL('./client.ts', import.meta.url).pathname,
    ).text();
    expect(supported(text)).toEqual(CLIENT);
  });

  it('keeps the plumbing out of both supported sets', async () => {
    const internal = await Bun.file(
      new URL('./internal.ts', import.meta.url).pathname,
    ).text();
    const both = new Set([...BARREL, ...CLIENT]);

    for (const name of supported(internal)) {
      expect({ name, supported: both.has(name) }).toEqual({
        name,
        supported: false,
      });
    }
  });
});
